# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Explore Data"
#  url = "explore"
#  weight = 10
#  identifier = "a-unique-reference"

#[[main]]
#  name = "Applications"
#  url = "explore/apps/"
#  weight = 11
#  parent = "a-unique-reference"

[[main]]
  name = "Datasets"
  url = "explore/datasets/"
  weight = 13
#  parent = "a-unique-reference"

[[main]]
  name = "Evidence"
  url = "app/visualization/"
  weight = 10
 # parent = "a-unique-reference"

[[main]]
  name = "Documentation"
  url = "documentation"
  weight = 20

#[[main]]
#  name = "Publications"
#  url = "publications"
#  weight = 30

[[main]]
  name = "Team"
  url = "team"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
